# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 09:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0002_auto_20170214_0942'),
        ('chat', '0002_auto_20170214_0942'),
        ('friendship', '0002_auto_20170214_0942'),
        ('likes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Chat')),
                ('like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='likes.Like')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friendship.Request')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
