# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='content',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
