# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'verbose_name': '\u0427\u0430\u0442', 'verbose_name_plural': '\u0427\u0430\u0442\u044b'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': '\u0421\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u0435', 'verbose_name_plural': '\u0421\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u044f'},
        ),
    ]
