# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 19:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_auto_20170214_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscribers', to=settings.AUTH_USER_MODEL),
        ),
    ]
