# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 18:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chat_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='subscribers',
            field=models.ManyToManyField(related_name='inchat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.Chat'),
        ),
    ]
