# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': '\u041b\u0430\u0439\u043a', 'verbose_name_plural': '\u041b\u0430\u0439\u043a\u0438'},
        ),
    ]
