# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friendship', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendship',
            options={'verbose_name': '\u0414\u0440\u0443\u0433', 'verbose_name_plural': '\u0414\u0440\u0443\u0437\u044c\u044f'},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name': '\u0417\u0430\u044f\u0432\u043a\u0430 \u0432 \u0434\u0440\u0443\u0437\u044c\u044f', 'verbose_name_plural': '\u0417\u0430\u044f\u0432\u043a\u0438 \u0432 \u0434\u0440\u0443\u0437\u044c\u044f'},
        ),
    ]
