# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 19:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('created_time', models.DateField(auto_now_add=True)),
                ('description', models.CharField(max_length=300)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u041d\u0430\u0433\u0440\u0430\u0434\u0430',
                'verbose_name_plural': '\u041d\u0430\u0433\u0440\u0430\u0434\u044b',
            },
        ),
    ]
